apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/name: k8svent
    app.kubernetes.io/part-of: k8svent
    atomist.com/workspaceId: T29E48P34
  name: k8svent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: role
    app.kubernetes.io/name: k8svent
    app.kubernetes.io/part-of: k8svent
    atomist.com/workspaceId: T29E48P34
  name: k8svent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/name: k8svent
    app.kubernetes.io/part-of: k8svent
    atomist.com/workspaceId: T29E48P34
  name: k8svent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8svent
subjects:
  - kind: ServiceAccount
    name: k8svent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: application
    app.kubernetes.io/name: k8svent
    app.kubernetes.io/part-of: k8svent
    atomist.com/workspaceId: T29E48P34
  name: k8svent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8svent
      atomist.com/workspaceId: T29E48P34
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: application
        app.kubernetes.io/name: k8svent
        app.kubernetes.io/part-of: k8svent
        app.kubernetes.io/version: "0"
        atomist.com/workspaceId: T29E48P34
    spec:
      containers:
        - env:
            - name: ATOMIST_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: k8svent
                  key: environment
            - name: K8SVENT_WEBHOOKS
              valueFrom:
                secretKeyRef:
                  name: k8svent
                  key: webhooks
            - name: K8SVENT_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: k8svent
                  key: secret
            - name: K8SVENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TMPDIR
              value: /tmp
          image: atomist/k8svent:0.13.1
          name: k8svent
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      securityContext:
        fsGroup: 2866
        runAsGroup: 2866
        runAsNonRoot: true
        runAsUser: 2866
      serviceAccountName: k8svent
      volumes:
        - emptyDir: {}
          name: tmp
